project_name: uptime-kuma-gchat-proxy

before:
  hooks:
    - go mod tidy

builds:
  - id: binaries
    binary: uptime-kuma-gchat-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    builds:
      - binaries
    replacements:
      amd64: x86_64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  use: git

